# Site settings
title: Mike Robinson
description: "I make stuff with Ruby on Rails and Javascript."
url: "http://mikerob215.github.io" # the base hostname & protocol for your site
destination: ../site/

# Build settings
markdown: kramdown
